Document: engage
Title: Debian engage Manual
Author: <insert document author here>
Abstract: This manual describes what engage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/engage/engage.sgml.gz

Format: postscript
Files: /usr/share/doc/engage/engage.ps.gz

Format: text
Files: /usr/share/doc/engage/engage.text.gz

Format: HTML
Index: /usr/share/doc/engage/html/index.html
Files: /usr/share/doc/engage/html/*.html
